import { POI, Coordinator, VibeOption, PreferenceQuestion } from './types';

export const vibeOptions: VibeOption[] = [
  { id: 'recharge', label: 'Recharge', emoji: '🧘', description: 'Relax, unwind, and rejuvenate' },
  { id: 'adventure', label: 'Adventure', emoji: '🏔️', description: 'Thrilling activities and exploration' },
  { id: 'romance', label: 'Romance', emoji: '💕', description: 'Romantic experiences for couples' },
  { id: 'culture', label: 'Culture Deep-Dive', emoji: '🏛️', description: 'Immerse in history and traditions' },
  { id: 'family', label: 'Family Fun', emoji: '👨‍👩‍👧', description: 'Kid-friendly experiences' },
  { id: 'spiritual', label: 'Spiritual', emoji: '🕉️', description: 'Temples, meditation, inner peace' },
  { id: 'nightlife', label: 'Nightlife', emoji: '🌙', description: 'Bars, clubs, evening entertainment' },
  { id: 'foodie', label: 'Foodie', emoji: '🍽️', description: 'Culinary adventures and local cuisine' },
];

export const rajasthanPOIs: POI[] = [
  {
    poiId: 'p_amber_fort',
    name: 'Amber Fort',
    city: 'Jaipur',
    description: 'Magnificent hilltop fortress with stunning Rajput architecture, mirror palace, and sprawling courtyards overlooking Maota Lake',
    vibeScores: { culture: 0.95, adventure: 0.4, romance: 0.3 },
    crowdLevel: 'high',
    openHours: { open: '08:00', close: '18:00' },
    cost: 350,
    lat: 26.9855,
    lng: 75.8513,
    imageUrl: 'https://images.unsplash.com/photo-1599661046289-e31897846e41?w=800&auto=format&fit=crop&q=80',
    category: 'attraction',
    tags: ['Heritage', 'Fort', 'Architecture', 'UNESCO'],
    rating: 4.7,
    estimatedDuration: 180,
  },
  {
    poiId: 'p_city_palace',
    name: 'City Palace',
    city: 'Jaipur',
    description: 'Royal residence and museum showcasing Rajasthani art, Mughal architecture, and the world\'s largest ceremonial sword. Still home to Jaipur royalty.',
    vibeScores: { culture: 0.9, recharge: 0.3, romance: 0.4 },
    crowdLevel: 'medium',
    openHours: { open: '09:30', close: '17:00' },
    cost: 500,
    lat: 26.9258,
    lng: 75.8237,
    imageUrl: 'https://images.unsplash.com/photo-1667099639128-4b10f464f4a2?w=800&auto=format&fit=crop&q=80',
    category: 'attraction',
    tags: ['Palace', 'Museum', 'Heritage', 'Royal'],
    rating: 4.5,
    estimatedDuration: 150,
  },
  {
    poiId: 'p_hawa_mahal',
    name: 'Hawa Mahal',
    city: 'Jaipur',
    description: 'Iconic pink sandstone palace with 953 honeycomb windows, built in 1799 for royal women to observe street life unseen. The crown jewel of Jaipur.',
    vibeScores: { culture: 0.85, romance: 0.5, adventure: 0.2 },
    crowdLevel: 'high',
    openHours: { open: '09:00', close: '17:30' },
    cost: 200,
    lat: 26.9239,
    lng: 75.8267,
    imageUrl: 'https://images.unsplash.com/photo-1772533254933-ee692487aba2?w=800&auto=format&fit=crop&q=80',
    category: 'attraction',
    tags: ['Iconic', 'Photography', 'Heritage', 'Pink City'],
    rating: 4.6,
    estimatedDuration: 60,
  },
  {
    poiId: 'p_jal_mahal',
    name: 'Jal Mahal',
    city: 'Jaipur',
    description: 'Breathtaking water palace floating serene in Man Sagar Lake, with Rajput architecture reflected in calm waters. A photographer\'s paradise at sunset.',
    vibeScores: { romance: 0.8, recharge: 0.7, culture: 0.5 },
    crowdLevel: 'low',
    openHours: { open: '06:00', close: '18:00' },
    cost: 100,
    lat: 26.9530,
    lng: 75.8462,
    imageUrl: 'https://images.unsplash.com/photo-1776966892086-c0f6cdf3380f?w=800&auto=format&fit=crop&q=80',
    category: 'attraction',
    tags: ['Lake', 'Scenic', 'Peaceful', 'Sunset'],
    rating: 4.4,
    estimatedDuration: 45,
  },
  {
    poiId: 'p_nahargarh_fort',
    name: 'Nahargarh Fort',
    city: 'Jaipur',
    description: 'Hilltop fort offering panoramic city views and a spectacular sunset point, with historic Madhavendra Bhawan palace inside.',
    vibeScores: { adventure: 0.7, romance: 0.6, culture: 0.6 },
    crowdLevel: 'medium',
    openHours: { open: '10:00', close: '17:30' },
    cost: 200,
    lat: 26.9387,
    lng: 75.8152,
    imageUrl: 'https://images.unsplash.com/photo-1477587458883-47145ed94245?w=800&auto=format&fit=crop&q=80',
    category: 'attraction',
    tags: ['Fort', 'Sunset', 'Views', 'Panoramic'],
    rating: 4.5,
    estimatedDuration: 120,
  },
  {
    poiId: 'p_johari_bazaar',
    name: 'Johari Bazaar',
    city: 'Jaipur',
    description: 'Famous jewelry and textile market in the heart of Pink City, offering Kundan, Meenakari, and Laadiki jewelry since the 18th century.',
    vibeScores: { foodie: 0.6, adventure: 0.4, culture: 0.7 },
    crowdLevel: 'high',
    openHours: { open: '10:00', close: '20:00' },
    cost: 0,
    lat: 26.9225,
    lng: 75.8270,
    imageUrl: 'https://images.unsplash.com/photo-1564501049412-61c2a3083791?w=800&auto=format&fit=crop&q=80',
    category: 'activity',
    tags: ['Shopping', 'Local', 'Markets', 'Jewelry'],
    rating: 4.3,
    estimatedDuration: 120,
  },
  {
    poiId: 'p_lmb_restaurant',
    name: 'Lassiwala & MORE',
    city: 'Jaipur',
    description: 'Legendary 1944 lassi shop and traditional Rajasthani thali restaurant serving authentic dal baati churma in a royal setting.',
    vibeScores: { foodie: 0.95, culture: 0.5, recharge: 0.3 },
    crowdLevel: 'medium',
    openHours: { open: '08:00', close: '22:00' },
    cost: 400,
    lat: 26.9230,
    lng: 75.8262,
    imageUrl: 'https://images.unsplash.com/photo-1565557623262-b51c2513a641?w=800&auto=format&fit=crop&q=80',
    category: 'restaurant',
    tags: ['Street Food', 'Traditional', 'Famous', 'Thali'],
    rating: 4.4,
    estimatedDuration: 60,
  },
  {
    poiId: 'p_udaipur_palace',
    name: 'City Palace Udaipur',
    city: 'Udaipur',
    description: 'Majestic lakeside palace complex with stunning Lake Pichola views, merged with Rajput and Mughal architectural styles. Largest palace in Rajasthan.',
    vibeScores: { romance: 0.9, culture: 0.85, recharge: 0.4 },
    crowdLevel: 'medium',
    openHours: { open: '09:30', close: '17:30' },
    cost: 500,
    lat: 24.5764,
    lng: 73.6913,
    imageUrl: 'https://images.unsplash.com/photo-1667099639128-4b10f464f4a2?w=800&auto=format&fit=crop&q=80',
    category: 'attraction',
    tags: ['Palace', 'Lake', 'Romantic', 'Royal'],
    rating: 4.8,
    estimatedDuration: 180,
  },
  {
    poiId: 'p_lake_pichola',
    name: 'Lake Pichola Boat Ride',
    city: 'Udaipur',
    description: 'Enchanting sunset boat ride on the iconic lake featuring Jag Niwas (Lake Palace) and Jag Mandir island palaces floating in crystal waters.',
    vibeScores: { romance: 0.95, recharge: 0.8, culture: 0.5 },
    crowdLevel: 'low',
    openHours: { open: '08:00', close: '18:00' },
    cost: 800,
    lat: 24.5710,
    lng: 73.6812,
    imageUrl: 'https://images.unsplash.com/photo-1534008897995-27a23e859048?w=800&auto=format&fit=crop&q=80',
    category: 'activity',
    tags: ['Boat', 'Sunset', 'Lake', 'Palace Views'],
    rating: 4.7,
    estimatedDuration: 90,
  },
  {
    poiId: 'p_saheliyon_ki_bari',
    name: 'Saheliyon Ki Bari',
    city: 'Udaipur',
    description: 'Garden of Maidens with stunning fountains, lotus pools, marble elephants, and colorful birds built for the royal ladies.',
    vibeScores: { recharge: 0.8, romance: 0.6, culture: 0.5 },
    crowdLevel: 'low',
    openHours: { open: '08:00', close: '18:00' },
    cost: 50,
    lat: 24.5904,
    lng: 73.6925,
    imageUrl: 'https://images.unsplash.com/photo-1527631746610-bca00a040d60?w=800&auto=format&fit=crop&q=80',
    category: 'attraction',
    tags: ['Garden', 'Peaceful', 'Royal', 'Fountains'],
    rating: 4.4,
    estimatedDuration: 60,
  },
  {
    poiId: 'p_udaipur_food_walk',
    name: 'Old City Food Walk',
    city: 'Udaipur',
    description: 'Guided walking tour through Udaipur\'s hidden culinary gems, from street vendors to century-old eateries serving authentic Mewari cuisine.',
    vibeScores: { foodie: 0.95, culture: 0.7, adventure: 0.5 },
    crowdLevel: 'medium',
    openHours: { open: '17:00', close: '21:00' },
    cost: 1200,
    lat: 24.5760,
    lng: 73.6850,
    imageUrl: 'https://images.unsplash.com/photo-1504674900247-0877df9cc836?w=800&auto=format&fit=crop&q=80',
    category: 'activity',
    tags: ['Food Tour', 'Walking', 'Local', 'Cuisine'],
    rating: 4.8,
    estimatedDuration: 180,
  },
  {
    poiId: 'p_jaisalmer_fort',
    name: 'Jaisalmer Fort',
    city: 'Jaisalmer',
    description: 'Living golden fort rising from the Thar Desert, one of the last "living forts" in the world with a vibrant township inside its sandstone walls.',
    vibeScores: { adventure: 0.8, culture: 0.9, romance: 0.4 },
    crowdLevel: 'medium',
    openHours: { open: '09:00', close: '18:00' },
    cost: 250,
    lat: 26.9124,
    lng: 70.9126,
    imageUrl: 'https://images.unsplash.com/photo-1506905925346-21bda4d32df4?w=800&auto=format&fit=crop&q=80',
    category: 'attraction',
    tags: ['Desert', 'Fort', 'Golden', 'Living Fort'],
    rating: 4.6,
    estimatedDuration: 180,
    bestTimeToVisit: 'October to March. Visit in late afternoon for golden light.',
    transportTip: 'Auto-rickshaw from city center ₹50. Fort is walkable from most hotels.',
    proTip: 'Explore the narrow lanes inside — locals live here! Visit Patwon Ki Haveli on the way. Evening rooftop views are magical.',
    nearbyAttractions: ['Patwon Ki Haveli', 'Gadisar Lake', 'Desert Safari Camp'],
    entryFeeDetails: '₹250 foreigners, ₹50 Indians. Camera ₹50 extra.',
  },
  {
    poiId: 'p_desert_safari',
    name: 'Thar Desert Safari',
    city: 'Jaisalmer',
    description: 'Epic camel safari through golden sand dunes with cultural performances, sunset dinner under the stars, and desert camping experience.',
    vibeScores: { adventure: 0.9, romance: 0.7, culture: 0.5 },
    crowdLevel: 'low',
    openHours: { open: '14:00', close: '22:00' },
    cost: 2500,
    lat: 26.8500,
    lng: 70.5000,
    imageUrl: 'https://images.unsplash.com/photo-1509316975850-ff9c5deb0cd9?w=800&auto=format&fit=crop&q=80',
    category: 'activity',
    tags: ['Camel', 'Desert', 'Sunset', 'Camping'],
    rating: 4.9,
    estimatedDuration: 300,
    bestTimeToVisit: 'October to March. Sunset safari (3-9 PM) is most popular.',
    transportTip: 'Camps are 42-56 km from Jaisalmer. Most operators provide pickup.',
    proTip: 'Carry sunscreen, sunglasses, and a scarf. The overnight camp with cultural show is worth the upgrade.',
    nearbyAttractions: ['Jaisalmer Fort', 'Bada Bagh', 'Kuldhara Ghost Village'],
    entryFeeDetails: '₹2,500-5,000 per person including camel ride, dinner, and cultural show.',
  },
  {
    poiId: 'p_patwon_ki_haveli',
    name: 'Patwon Ki Haveli',
    city: 'Jaisalmer',
    description: 'Intricately carved sandstone mansion complex with five separate havelis showcasing exquisite Jain architecture and mirror work.',
    vibeScores: { culture: 0.85, romance: 0.3, recharge: 0.3 },
    crowdLevel: 'low',
    openHours: { open: '08:00', close: '18:00' },
    cost: 100,
    lat: 26.9060,
    lng: 70.9145,
    imageUrl: 'https://images.unsplash.com/photo-1596401057633-54a8fe8ef647?w=800&auto=format&fit=crop&q=80',
    category: 'attraction',
    tags: ['Heritage', 'Carvings', 'Architecture', 'Jain'],
    rating: 4.3,
    estimatedDuration: 60,
    bestTimeToVisit: 'Morning (8-10 AM) for best light through carved windows',
    transportTip: '500m from Jaisalmer Fort. Walk or take a cycle-rickshaw.',
    proTip: 'The first haveli has the best carvings. Look up at the ceilings — they are intricate masterpieces.',
    nearbyAttractions: ['Jaisalmer Fort', 'Gadisar Lake', 'Nathmal Ki Haveli'],
    entryFeeDetails: '₹100 per person. Guide available for ₹100 extra.',
  },
  {
    poiId: 'p_gadisar_lake',
    name: 'Gadisar Lake',
    city: 'Jaisalmer',
    description: 'Historic rainwater lake surrounded by temples and ghats, once the only water source for the royal city, now a serene sunset spot.',
    vibeScores: { recharge: 0.7, romance: 0.6, culture: 0.5 },
    crowdLevel: 'low',
    openHours: { open: '06:00', close: '19:00' },
    cost: 0,
    lat: 26.9080,
    lng: 70.9130,
    imageUrl: 'https://images.unsplash.com/photo-1436491865332-7a61a109cc05?w=800&auto=format&fit=crop&q=80',
    category: 'location',
    tags: ['Lake', 'Sunset', 'Peaceful', 'Temples'],
    rating: 4.4,
    estimatedDuration: 60,
    bestTimeToVisit: 'Sunset (5-6 PM) for golden light on fort reflections',
    transportTip: '1.5 km from Jaisalmer Fort. Walk or cycle-rickshaw ₹30.',
    proTip: 'Take a boat ride (₹50-100). The island temple in the middle is photogenic. Artists sell miniature paintings here.',
    nearbyAttractions: ['Jaisalmer Fort', 'Patwon Ki Haveli', 'Desert Cultural Centre'],
    entryFeeDetails: 'Free entry. Boat rides ₹50-100.',
  },
  {
    poiId: 'p_niwas_haveli',
    name: 'Niwas Haveli Heritage Stay',
    city: 'Jaisalmer',
    description: 'Restored 19th-century haveli with breathtaking rooftop views of the golden fort, featuring traditional decor and royal hospitality.',
    vibeScores: { culture: 0.8, recharge: 0.6, romance: 0.5 },
    crowdLevel: 'low',
    openHours: { open: '00:00', close: '23:59' },
    cost: 4500,
    lat: 26.9130,
    lng: 70.9120,
    imageUrl: 'https://images.unsplash.com/photo-1566073771259-6a8506099945?w=800&auto=format&fit=crop&q=80',
    category: 'hotel',
    tags: ['Heritage', 'Boutique', 'Rooftop', 'Luxury'],
    rating: 4.7,
    estimatedDuration: 0,
    bestTimeToVisit: 'October to March for pleasant weather',
    transportTip: 'In the heart of Jaisalmer. Walk from the fort or bus stand.',
    proTip: 'Book the rooftop room for fort views. The traditional Rajasthani dinner is included and delicious.',
    nearbyAttractions: ['Jaisalmer Fort', 'Gadisar Lake', 'Patwon Ki Haveli'],
    entryFeeDetails: '₹4,500-8,000 per night including breakfast and dinner.',
  },
];

export const goaPOIs: POI[] = [
  {
    poiId: 'p_calangute_beach',
    name: 'Calangute Beach',
    city: 'Goa',
    description: 'The Queen of Beaches — a sprawling golden shoreline with vibrant shacks, water sports, and a lively nightlife scene along the Arabian Sea coast.',
    vibeScores: { nightlife: 0.8, adventure: 0.7, recharge: 0.5 },
    crowdLevel: 'high',
    openHours: { open: '06:00', close: '22:00' },
    cost: 0,
    lat: 15.5584,
    lng: 73.8010,
    imageUrl: 'https://images.unsplash.com/photo-1506929562872-bb421503ef21?w=800&auto=format&fit=crop&q=80',
    category: 'attraction',
    tags: ['Beach', 'Water Sports', 'Nightlife', 'Shacks'],
    rating: 4.3,
    estimatedDuration: 240,
    bestTimeToVisit: 'November to February for perfect weather. Avoid monsoon (Jun-Sep).',
    transportTip: '30 km from Panaji. Bus ₹50 from Mapusa. Taxis ₹400-600.',
    proTip: 'Goa Tourism water sports are regulated — use only licensed operators. Try parasailing and jet skiing.',
    nearbyAttractions: ['Baga Beach', 'Fort Aguada', 'Titos Lane'],
    entryFeeDetails: 'Free entry. Water sports ₹500-2,000.',
  },
  {
    poiId: 'p_basilica_bom_jesus',
    name: 'Basilica of Bom Jesus',
    city: 'Old Goa',
    description: 'UNESCO World Heritage church housing the mortal remains of St. Francis Xavier. A masterpiece of Portuguese Baroque architecture with silver casket reliquary.',
    vibeScores: { culture: 0.95, spiritual: 0.8, architecture: 0.9 },
    crowdLevel: 'medium',
    openHours: { open: '06:00', close: '18:00' },
    cost: 50,
    lat: 15.4960,
    lng: 73.9531,
    imageUrl: 'https://images.unsplash.com/photo-1667760334198-d3958029a08b?w=800&auto=format&fit=crop&q=80',
    category: 'attraction',
    tags: ['Church', 'UNESCO', 'Baroque', 'Relics', 'Heritage'],
    rating: 4.7,
    estimatedDuration: 90,
    bestTimeToVisit: 'December 4th (Feast of St. Francis Xavier) for special celebrations',
    transportTip: '9 km from Panaji. Bus ₹15 from Mapusa. Taxis ₹200-300.',
    proTip: 'Dress modestly (cover shoulders and knees). The silver casket is on display in the upper chapel.',
    nearbyAttractions: ['Se Cathedral', 'Church of St. Francis of Assisi', 'Archaeological Museum'],
    entryFeeDetails: 'Free entry. Camera ₹50. Upper chapel access ₹25.',
  },
  {
    poiId: 'p_fort_aguada',
    name: 'Fort Aguada',
    city: 'Goa',
    description: '17th-century Portuguese fort overlooking the Arabian Sea with a panoramic lighthouse, built to defend against Dutch and Maratha invasions.',
    vibeScores: { culture: 0.8, adventure: 0.6, romance: 0.7 },
    crowdLevel: 'low',
    openHours: { open: '09:00', close: '18:00' },
    cost: 100,
    lat: 15.4747,
    lng: 73.8316,
    imageUrl: 'https://images.unsplash.com/photo-1544551763-46a013bb70d5?w=800&auto=format&fit=crop&q=80',
    category: 'attraction',
    tags: ['Fort', 'Lighthouse', 'Heritage', 'Sea Views'],
    rating: 4.5,
    estimatedDuration: 120,
    bestTimeToVisit: 'Late afternoon for sunset views from the ramparts',
    transportTip: '13 km from Panaji. Taxis ₹300-400. Bus from Mapusa.',
    proTip: 'The lighthouse is the oldest in Asia (1864). Climb up for 360-degree views of the Arabian Sea.',
    nearbyAttractions: ['Sinquerim Beach', 'Taj Fort Aguada Resort', 'Baga Beach'],
    entryFeeDetails: '₹100 foreigners, ₹25 Indians. Lighthouse ₹50 extra.',
  },
  {
    poiId: 'p_spice_plantation',
    name: 'Sahakari Spice Plantation',
    city: 'Ponda',
    description: 'Lush tropical spice farm showcasing vanilla, cardamom, pepper, and nutmeg cultivation with traditional Goan cooking demonstrations and authentic food tasting.',
    vibeScores: { foodie: 0.9, culture: 0.8, recharge: 0.7 },
    crowdLevel: 'low',
    openHours: { open: '09:00', close: '17:00' },
    cost: 600,
    lat: 15.2700,
    lng: 73.9100,
    imageUrl: 'https://images.unsplash.com/photo-1596401057633-54a8fe8ef647?w=800&auto=format&fit=crop&q=80',
    category: 'activity',
    tags: ['Spices', 'Food', 'Farm', 'Cooking'],
    rating: 4.5,
    estimatedDuration: 120,
    bestTimeToVisit: 'Year-round. Monsoon season (Jun-Sep) is lush and green.',
    transportTip: '26 km from Panaji. Taxis ₹500-600. Self-drive recommended.',
    proTip: 'The traditional Goan lunch buffet is included. Try the feni (local spirit) tasting.',
    nearbyAttractions: ['Ponda Temples', 'Bhagwan Mahavir Wildlife Sanctuary', 'Dudhsagar Falls'],
    entryFeeDetails: '₹600 per person including guided tour, lunch, and spice shopping.',
  },
  {
    poiId: 'p_anjuna_beach',
    name: 'Anjuna Beach',
    city: 'Goa',
    description: 'Legendary flea market beach famous for its Wednesday market, bohemian vibes, trance music heritage, and stunning sunset cliffs along the coastline.',
    vibeScores: { nightlife: 0.7, culture: 0.6, adventure: 0.5 },
    crowdLevel: 'medium',
    openHours: { open: '08:00', close: '20:00' },
    cost: 0,
    lat: 15.5596,
    lng: 73.7928,
    imageUrl: 'https://images.unsplash.com/photo-1564501049412-61c2a3083791?w=800&auto=format&fit=crop&q=80',
    category: 'activity',
    tags: ['Market', 'Bohemian', 'Cliffs', 'Sunset'],
    rating: 4.4,
    estimatedDuration: 180,
    bestTimeToVisit: 'Wednesday for the famous flea market. Evenings for sunset.',
    transportTip: '18 km from Panaji. Bus ₹30 from Mapusa. Taxis ₹300.',
    proTip: 'The Wednesday market starts at noon — go early for the best deals. Western.arc has great sunset views.',
    nearbyAttractions: ['Vagator Beach', 'Chapora Fort', 'Ozran Beach'],
    entryFeeDetails: 'Free entry. Market prices vary — bargain!',
  },
  {
    poiId: 'p_dudhsagar_falls',
    name: 'Dudhsagar Falls',
    city: 'Goa',
    description: 'Majestic four-tiered waterfall towering 310 meters, meaning "Sea of Milk," cascading through the Western Ghats — best viewed during monsoon season.',
    vibeScores: { adventure: 0.85, recharge: 0.7, nature: 0.9 },
    crowdLevel: 'low',
    openHours: { open: '06:00', close: '18:00' },
    cost: 200,
    lat: 15.2760,
    lng: 74.3080,
    imageUrl: 'https://images.unsplash.com/photo-1667760334198-d3958029a08b?w=800&auto=format&fit=crop&q=80',
    category: 'attraction',
    tags: ['Waterfall', 'Nature', 'Monsoon', 'Ghats'],
    rating: 4.8,
    estimatedDuration: 180,
    bestTimeToVisit: 'Monsoon (Jun-Sep) for full flow. Winter for swimming.',
    transportTip: '60 km from Panaji. Jeep safari ₹500-800. Train to Kulem then jeep.',
    proTip: 'Wear sturdy shoes — it\'s a 2 km hike from the parking. The jeep ride through Bhagwan Mahavir sanctuary is thrilling.',
    nearbyAttractions: ['Bhagwan Mahavir Wildlife Sanctuary', 'Molem', 'Tropical Spice Plantation'],
    entryFeeDetails: '₹200 entry + ₹500-800 jeep safari. Swimming free.',
  },
  {
    poiId: 'p_palolem_beach',
    name: 'Palolem Beach',
    city: 'South Goa',
    description: 'Picturesque crescent-shaped beach tucked between coconut groves with serene Arabian waters, dolphin-spotting boat rides, and intimate beach shacks.',
    vibeScores: { recharge: 0.9, romance: 0.7, nature: 0.8 },
    crowdLevel: 'low',
    openHours: { open: '06:00', close: '20:00' },
    cost: 0,
    lat: 15.1290,
    lng: 74.0222,
    imageUrl: 'https://images.unsplash.com/photo-1506929562872-bb421503ef21?w=800&auto=format&fit=crop&q=80',
    category: 'attraction',
    tags: ['Beach', 'Crescent', 'Dolphin', 'Peaceful'],
    rating: 4.6,
    estimatedDuration: 240,
    bestTimeToVisit: 'November to February. Early morning for dolphin spotting.',
    transportTip: '67 km from Panaji. Bus ₹80 from Madgaon. Taxis ₹800-1,000.',
    proTip: 'The silent disco on the beach is unique. Kayak to the island for a private beach experience.',
    nearbyAttractions: ['Butterfly Beach', 'Cabo de Rama Fort', 'Agonda Beach'],
    entryFeeDetails: 'Free entry. Dolphin spotting ₹500-700 per person.',
  },
  {
    poiId: 'p_old_goa_churches',
    name: 'Old Goa Heritage Walk',
    city: 'Old Goa',
    description: 'UNESCO heritage trail through the former capital of Portuguese India — Se Cathedral, Church of St. Francis of Assisi, and the Archaeological Museum.',
    vibeScores: { culture: 0.95, spiritual: 0.7, architecture: 0.9 },
    crowdLevel: 'medium',
    openHours: { open: '08:00', close: '18:00' },
    cost: 150,
    lat: 15.4970,
    lng: 73.9550,
    imageUrl: 'https://images.unsplash.com/photo-1560448204-e02f11c3d0e2?w=800&auto=format&fit=crop&q=80',
    category: 'activity',
    tags: ['UNESCO', 'Portuguese', 'Heritage', 'Churches'],
    rating: 4.7,
    estimatedDuration: 180,
    bestTimeToVisit: 'Morning (8-11 AM) to avoid heat. December for Christmas celebrations.',
    transportTip: '9 km from Panaji. Bus ₹15. Taxis ₹200. Auto-rickshaw ₹150.',
    proTip: 'Se Cathedral is the largest church in Asia. The Archaeological Museum has stunning Hindu temple artifacts.',
    nearbyAttractions: ['Basilica of Bom Jesus', 'Se Cathedral', 'Museum of Christian Art'],
    entryFeeDetails: 'Free entry to churches. Museum ₹25.',
  },
];

export const keralaPOIs: POI[] = [
  {
    poiId: 'p_alleppey_backwaters',
    name: 'Alleppey Houseboat Cruise',
    city: 'Alleppey',
    description: 'Iconic overnight houseboat cruise through Kerala\'s enchanting network of lagoons, canals, and lakes, passing lush paddy fields and traditional villages.',
    vibeScores: { recharge: 0.95, romance: 0.8, culture: 0.6 },
    crowdLevel: 'low',
    openHours: { open: '08:00', close: '22:00' },
    cost: 6000,
    lat: 9.6300,
    lng: 76.3500,
    imageUrl: 'https://images.unsplash.com/photo-1548574505-5e239809ee19?w=800&auto=format&fit=crop&q=80',
    category: 'activity',
    tags: ['Houseboat', 'Backwaters', 'Overnight', 'Village Life'],
    rating: 4.9,
    estimatedDuration: 480,
    bestTimeToVisit: 'September to March. Monsoon (Jun-Aug) is magical but rainy.',
    transportTip: '1.5 hrs from Cochin. Taxis ₹1,500-2,000. Alleppey bus stand is well connected.',
    proTip: 'Book premium houseboats for AC and private deck. The overnight cruise includes Kerala-style dinner on board.',
    nearbyAttractions: ['Marari Beach', 'Alappuzha Lighthouse', 'Krishnapuram Palace'],
    entryFeeDetails: '₹6,000-15,000 per night including meals. Day cruise ₹1,500-3,000.',
  },
  {
    poiId: 'p_munnar_tea_gardens',
    name: 'Munnar Tea Plantations',
    city: 'Munnar',
    description: 'Breathtaking rolling hills of endless tea estates in the Western Ghats, with cascading valleys, misty mornings, and the world\'s largest tea plantation.',
    vibeScores: { recharge: 0.9, culture: 0.7, nature: 0.95 },
    crowdLevel: 'medium',
    openHours: { open: '06:00', close: '18:00' },
    cost: 500,
    lat: 10.0874,
    lng: 77.0810,
    imageUrl: 'https://images.unsplash.com/photo-1544005313-94ddf0286df2?w=800&auto=format&fit=crop&q=80',
    category: 'attraction',
    tags: ['Tea', 'Mountains', 'Nature', 'Western Ghats'],
    rating: 4.8,
    estimatedDuration: 240,
    bestTimeToVisit: 'September to May. Misty mornings are magical.',
    transportTip: '4 hrs from Cochin. Buses ₹200. Taxis ₹2,500-3,500.',
    proTip: 'Visit the Tea Museum (₹125) for a factory tour. Eravikulam National Park is 15 km away.',
    nearbyAttractions: ['Eravikulam National Park', 'Tea Museum', 'Top Station'],
    entryFeeDetails: 'Plantation visits free. Tea Museum ₹125. Eravikulam ₹120.',
  },
  {
    poiId: 'p_periyar_wildlife',
    name: 'Periyar Wildlife Sanctuary',
    city: 'Thekkady',
    description: 'India\'s premier tiger reserve and elephant sanctuary set around the pristine Periyar Lake, with bamboo forests, boat safaris, and incredible biodiversity.',
    vibeScores: { adventure: 0.8, culture: 0.5, nature: 0.95 },
    crowdLevel: 'low',
    openHours: { open: '06:00', close: '18:00' },
    cost: 500,
    lat: 9.5000,
    lng: 77.2500,
    imageUrl: 'https://images.unsplash.com/photo-1544005313-94ddf0286df2?w=800&auto=format&fit=crop&q=80',
    category: 'activity',
    tags: ['Wildlife', 'Safari', 'Tiger', 'Elephant'],
    rating: 4.6,
    estimatedDuration: 180,
    bestTimeToVisit: 'October to March. Early morning boat safari for best wildlife sightings.',
    transportTip: '4 hrs from Cochin. Buses ₹250. Taxis ₹3,000.',
    proTip: 'Book boat safari tickets online in advance — they sell out fast. Bamboo rafting is a great alternative.',
    nearbyAttractions: ['Spice Plantations', 'Kumily', 'Vandiperiyar'],
    entryFeeDetails: '₹250 boat safari, ₹100 entry, ₹50 camera. Trekking ₹300-500.',
  },
  {
    poiId: 'p_padmanabhaswamy',
    name: 'Padmanabhaswamy Temple',
    city: 'Thiruvananthapuram',
    description: 'One of the richest temples in the world, an architectural masterpiece of Dravidian style with a 100-foot golden gopuram and sacred inner sanctum.',
    vibeScores: { spiritual: 0.95, culture: 0.9, architecture: 0.9 },
    crowdLevel: 'high',
    openHours: { open: '05:00', close: '12:00' },
    cost: 0,
    lat: 8.5042,
    lng: 76.9440,
    imageUrl: 'https://images.unsplash.com/photo-1560448204-e02f11c3d0e2?w=800&auto=format&fit=crop&q=80',
    category: 'attraction',
    tags: ['Temple', 'Spiritual', 'Dravidian', 'Gold'],
    rating: 4.8,
    estimatedDuration: 90,
    bestTimeToVisit: 'Early morning (5-7 AM) for a peaceful darshan. Festival days are spectacular.',
    transportTip: 'In the heart of Trivandrum. Walk from any hotel. No parking nearby.',
    proTip: 'Dress code strictly enforced — men: mundu, women: saree or churidar. Lockers available for phones/cameras.',
    nearbyAttractions: ['Napier Museum', 'Kovalam Beach', 'Shanghumukham Beach'],
    entryFeeDetails: 'Free entry. Special darshan ₹50-200. Vault access restricted.',
  },
  {
    poiId: 'p_kovalam_beach',
    name: 'Kovalam Beach',
    city: 'Thiruvananthapuram',
    description: 'India\'s premier beach destination with three crescent beaches, Ayurvedic massage centres, lighthouse views, and pristine waters of the Indian Ocean.',
    vibeScores: { recharge: 0.9, romance: 0.7, nightlife: 0.3 },
    crowdLevel: 'medium',
    openHours: { open: '06:00', close: '20:00' },
    cost: 0,
    lat: 8.5005,
    lng: 76.9700,
    imageUrl: 'https://images.unsplash.com/photo-1518548419970-58e3b4079ab2?w=800&auto=format&fit=crop&q=80',
    category: 'attraction',
    tags: ['Beach', 'Ayurveda', 'Lighthouse', 'Ocean'],
    rating: 4.5,
    estimatedDuration: 240,
    bestTimeToVisit: 'November to February. Sunset from lighthouse is spectacular.',
    transportTip: '16 km from Trivandrum. Taxis ₹300-400. Buses ₹20.',
    proTip: 'Lighthouse Beach is the most scenic. Ayurvedic massages on the beach ₹800-1,500.',
    nearbyAttractions: ['Padmanabhaswamy Temple', 'Vizhinjam Mosque', 'Light House'],
    entryFeeDetails: 'Free. Lighthouse ₹20. Ayurveda ₹800-3,000.',
  },
  {
    poiId: 'p_wayanad',
    name: 'Wayanad Wildlife',
    city: 'Wayanad',
    description: 'Serene hill station with ancient caves, dense forests, spice-scented plantations, and wildlife sanctuaries nestled in the Sahyadri mountain range.',
    vibeScores: { recharge: 0.9, adventure: 0.6, culture: 0.7 },
    crowdLevel: 'low',
    openHours: { open: '06:00', close: '18:00' },
    cost: 300,
    lat: 11.6970,
    lng: 76.2210,
    imageUrl: 'https://images.unsplash.com/photo-1544005313-94ddf0286df2?w=800&auto=format&fit=crop&q=80',
    category: 'attraction',
    tags: ['Caves', 'Forests', 'Spices', 'Hill Station'],
    rating: 4.7,
    estimatedDuration: 180,
    bestTimeToVisit: 'October to May. Edakkal Caves are closed during heavy monsoon.',
    transportTip: '3 hrs from Cochin. Buses ₹200. Taxis ₹2,500.',
    proTip: 'Edakkal Caves have 6,000-year-old petroglyphs. The chain tree walk is thrilling. Try local Kerala coffee.',
    nearbyAttractions: ['Edakkal Caves', 'Banasura Sagar Dam', 'Chembra Peak'],
    entryFeeDetails: 'Caves ₹80, Wildlife sanctuary ₹150, Boating ₹100-300.',
  },
  {
    poiId: 'p_fort_kochi',
    name: 'Fort Kochi Heritage',
    city: 'Kochi',
    description: 'Historic colonial quarter with Chinese fishing nets, Portuguese and Dutch architecture, vibrant art galleries, and the famous Kathakali dance performances on the waterfront.',
    vibeScores: { culture: 0.95, romance: 0.7, foodie: 0.8 },
    crowdLevel: 'medium',
    openHours: { open: '08:00', close: '20:00' },
    cost: 100,
    lat: 9.9700,
    lng: 76.2400,
    imageUrl: 'https://images.unsplash.com/photo-1560448204-e02f11c3d0e2?w=800&auto=format&fit=crop&q=80',
    category: 'activity',
    tags: ['Colonial', 'Chinese Nets', 'Art', 'Dance'],
    rating: 4.6,
    estimatedDuration: 180,
    bestTimeToVisit: 'October to March. Kochi-Muziris Biennale (Dec-Mar) is world-class.',
    transportTip: 'Walk from Ernakulam ferry. Or take auto-rickshaw ₹50-100.',
    proTip: 'The Chinese fishing nets at sunset are iconic. Catch a Kathakali performance at 5 PM at the Kerala Kathakali Centre.',
    nearbyAttractions: ['Chinese Fishing Nets', 'St. Francis Church', 'Mattancherry Palace'],
    entryFeeDetails: 'Walking free. Kathakali show ₹300-500. Museum ₹5-25.',
  },
  {
    poiId: 'p_ayurveda_kerela',
    name: 'Ayurveda Wellness Retreat',
    city: 'Kerala',
    description: 'Authentic Ayurvedic healing experience with Panchakarma therapies, herbal oil massages, yoga sessions, and yoga in a serene setting.',
    vibeScores: { recharge: 0.95, spiritual: 0.8, wellness: 0.9 },
    crowdLevel: 'low',
    openHours: { open: '07:00', close: '19:00' },
    cost: 8000,
    lat: 9.5000,
    lng: 76.0000,
    imageUrl: 'https://images.unsplash.com/photo-1544367567-0f2fcb009e0b?w=800&auto=format&fit=crop&q=80',
    category: 'activity',
    tags: ['Ayurveda', 'Healing', 'Spa', 'Wellness'],
    rating: 4.9,
    estimatedDuration: 480,
    bestTimeToVisit: 'June to September (monsoon) for Panchakarma. Year-round for relaxation.',
    transportTip: 'Multiple locations across Kerala. Most retreats offer airport pickup.',
    proTip: 'Minimum 7 days recommended for Panchakarma. Vegetarian diet is part of the treatment.',
    nearbyAttractions: ['Backwaters', 'Beaches', 'Spice Plantations'],
    entryFeeDetails: '₹8,000-50,000 per day including accommodation, meals, and treatments.',
  },
];

export const sampleCoordinators: Coordinator[] = [
  {
    coordinatorId: 'coord_1',
    name: 'Priya Sharma',
    photo: 'https://images.unsplash.com/photo-1494790108377-be9c29b29330?w=200&auto=format&fit=crop&q=60',
    languages: ['Hindi', 'English', 'Rajasthani'],
    expertise: ['Heritage', 'Architecture', 'Photography'],
    location: { lat: 26.9200, lng: 75.8200 },
    rating: 4.9,
    workload: 2,
    availability: [],
    bio: 'Born and raised in Jaipur, passionate about sharing the stories behind every fort and palace.',
  },
  {
    coordinatorId: 'coord_2',
    name: 'Arjun Singh',
    photo: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=200&auto=format&fit=crop&q=60',
    languages: ['Hindi', 'English', 'French'],
    expertise: ['Desert', 'Adventure', 'Camping'],
    location: { lat: 26.9100, lng: 70.9100 },
    rating: 4.7,
    workload: 1,
    availability: [],
    bio: 'Desert expert and adventure guide with 8 years of experience in the Thar.',
  },
  {
    coordinatorId: 'coord_3',
    name: 'Meera Patel',
    photo: 'https://images.unsplash.com/photo-1438761681033-6461ffad8d80?w=200&auto=format&fit=crop&q=60',
    languages: ['Hindi', 'English', 'Gujarati'],
    expertise: ['Food', 'Culture', 'Shopping'],
    location: { lat: 24.5800, lng: 73.6900 },
    rating: 4.8,
    workload: 3,
    availability: [],
    bio: 'Foodie at heart, I\'ll take you to the best hidden culinary gems of Rajasthan.',
  },
  {
    coordinatorId: 'coord_4',
    name: 'Rita D\'Souza',
    photo: 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?w=200&auto=format&fit=crop&q=60',
    languages: ['Konkani', 'English', 'Hindi'],
    expertise: ['Beaches', 'Heritage', 'Portuguese Culture'],
    location: { lat: 15.5000, lng: 73.9000 },
    rating: 4.8,
    workload: 2,
    availability: [],
    bio: 'Goan local with deep knowledge of Portuguese heritage and the best beaches along the coastline.',
  },
  {
    coordinatorId: 'coord_5',
    name: 'Lakshmi Menon',
    photo: 'https://images.unsplash.com/photo-1438761681033-6461ffad8d80?w=200&auto=format&fit=crop&q=60',
    languages: ['Malayalam', 'English', 'Tamil'],
    expertise: ['Ayurveda', 'Backwaters', 'Temples'],
    location: { lat: 9.5000, lng: 76.0000 },
    rating: 4.9,
    workload: 3,
    availability: [],
    bio: 'Kerala native and certified Ayurvedic therapist with 15 years of experience in traditional healing.',
  },
];

export const preferenceQuestions: PreferenceQuestion[] = [
  {
    id: 'trip_type',
    type: 'multi',
    question: 'What kind of trip are you craving?',
    options: [
      { value: 'recharge', label: 'Recharge', emoji: '🧘' },
      { value: 'adventure', label: 'Adventure', emoji: '🏔️' },
      { value: 'culture', label: 'Culture Deep-Dive', emoji: '🏛️' },
      { value: 'family', label: 'Family Fun', emoji: '👨‍👩‍👧' },
      { value: 'romance', label: 'Romance', emoji: '💕' },
      { value: 'foodie', label: 'Foodie', emoji: '🍽️' },
    ],
  },
  {
    id: 'budget',
    type: 'single',
    question: "What's your budget comfort zone?",
    options: [
      { value: 'budget', label: 'Budget-Friendly', emoji: '💰' },
      { value: 'mid', label: 'Balanced', emoji: '💎' },
      { value: 'luxury', label: 'Premium', emoji: '👑' },
    ],
  },
  {
    id: 'pace',
    type: 'single',
    question: 'How do you like to travel?',
    options: [
      { value: 'relaxed', label: 'Relaxed', emoji: '🌴' },
      { value: 'balanced', label: 'Balanced', emoji: '⚖️' },
      { value: 'packed', label: 'Pack it all in', emoji: '⚡' },
    ],
  },
  {
    id: 'interests',
    type: 'multi',
    question: 'Pick your interests (select all that apply)',
    options: [
      { value: 'heritage', label: 'Heritage & History' },
      { value: 'nature', label: 'Nature & Landscapes' },
      { value: 'food', label: 'Local Cuisine' },
      { value: 'shopping', label: 'Shopping & Markets' },
      { value: 'photography', label: 'Photography' },
      { value: 'wellness', label: 'Wellness & Spa' },
    ],
  },
  {
    id: 'dietary',
    type: 'single',
    question: 'Any dietary preferences?',
    options: [
      { value: 'no_restriction', label: 'No restrictions' },
      { value: 'vegetarian', label: 'Vegetarian' },
      { value: 'vegan', label: 'Vegan' },
      { value: 'halal', label: 'Halal' },
    ],
  },
  {
    id: 'special_needs',
    type: 'text',
    question: 'Anything else we should know? (accessibility needs, must-sees, allergies...)',
    placeholder: 'e.g., "I need wheelchair access, love textiles, and hate crowds"',
  },
];

export const destinations = [
  { id: 'rajasthan', name: 'Rajasthan', tagline: 'Royal Heritage & Desert Adventures', emoji: '🏰' },
  { id: 'kerala', name: 'Kerala', tagline: 'Backwaters & Ayurvedic Bliss', emoji: '🌴' },
  { id: 'goa', name: 'Goa', tagline: 'Beaches & Portuguese Heritage', emoji: '🏖️' },
];

export const allPOIs = [...rajasthanPOIs, ...goaPOIs, ...keralaPOIs];
