export const PLACEHOLDER_IMAGES = {
  amberFort: 'linear-gradient(135deg, #f59e0b, #d97706)',
  cityPalace: 'linear-gradient(135deg, #f43f5e, #be185d)',
  hawaMahal: 'linear-gradient(135deg, #ec4899, #db2777)',
  jalMahal: 'linear-gradient(135deg, #0ea5e9, #0369a1)',
  nahargarh: 'linear-gradient(135deg, #8b5cf6, #6d28d9)',
  johari: 'linear-gradient(135deg, #f97316, #ea580c)',
  lassi: 'linear-gradient(135deg, #84cc16, #4d7c0f)',
  udaipur: 'linear-gradient(135deg, #0d9488, #0f766e)',
  pichola: 'linear-gradient(135deg, #06b6d4, #0891b2)',
  saheliyon: 'linear-gradient(135deg, #22c55e, #15803d)',
  foodWalk: 'linear-gradient(135deg, #eab308, #a16207)',
  jaisalmer: 'linear-gradient(135deg, #fbbf24, #b45309)',
  desert: 'linear-gradient(135deg, #fcd34d, #b45309)',
  haveli: 'linear-gradient(135deg, #d4a373, #a4723b)',
  gadisar: 'linear-gradient(135deg, #38bdf8, #0284c7)',
  niwas: 'linear-gradient(135deg, #c084fc, #7e22ce)',
  calangute: 'linear-gradient(135deg, #f97316, #ea580c)',
  basilica: 'linear-gradient(135deg, #6366f1, #4f46e5)',
  fortAguada: 'linear-gradient(135deg, #0ea5e9, #0369a1)',
  spicePlantation: 'linear-gradient(135deg, #84cc16, #4d7c0f)',
  anjuna: 'linear-gradient(135deg, #ec4899, #db2777)',
  dudhsagar: 'linear-gradient(135deg, #38bdf8, #0284c7)',
  palolem: 'linear-gradient(135deg, #10b981, #059669)',
  oldGoa: 'linear-gradient(135deg, #6366f1, #4f46e5)',
  alleppey: 'linear-gradient(135deg, #14b8a6, #0d9488)',
  munnar: 'linear-gradient(135deg, #22c55e, #16a34a)',
  periyar: 'linear-gradient(135deg, #f59e0b, #d97706)',
  padmanabha: 'linear-gradient(135deg, #fbbf24, #b45309)',
  kovalam: 'linear-gradient(135deg, #0ea5e9, #0369a1)',
  wayanad: 'linear-gradient(135deg, #10b981, #059669)',
  fortKochi: 'linear-gradient(135deg, #8b5cf6, #6d28d9)',
  ayurveda: 'linear-gradient(135deg, #14b8a6, #0d9488)',
} as const;

export type PlaceholderImageKey = keyof typeof PLACEHOLDER_IMAGES;

export function getImageForPoi(poiId: string): string {
  const mapping: Record<string, string> = {
    p_amber_fort: PLACEHOLDER_IMAGES.amberFort,
    p_city_palace: PLACEHOLDER_IMAGES.cityPalace,
    p_hawa_mahal: PLACEHOLDER_IMAGES.hawaMahal,
    p_jal_mahal: PLACEHOLDER_IMAGES.jalMahal,
    p_nahargarh_fort: PLACEHOLDER_IMAGES.nahargarh,
    p_johari_bazaar: PLACEHOLDER_IMAGES.johari,
    p_lmb_restaurant: PLACEHOLDER_IMAGES.lassi,
    p_udaipur_palace: PLACEHOLDER_IMAGES.udaipur,
    p_lake_pichola: PLACEHOLDER_IMAGES.pichola,
    p_saheliyon_ki_bari: PLACEHOLDER_IMAGES.saheliyon,
    p_udaipur_food_walk: PLACEHOLDER_IMAGES.foodWalk,
    p_jaisalmer_fort: PLACEHOLDER_IMAGES.jaisalmer,
    p_desert_safari: PLACEHOLDER_IMAGES.desert,
    p_patwon_ki_haveli: PLACEHOLDER_IMAGES.haveli,
    p_gadisar_lake: PLACEHOLDER_IMAGES.gadisar,
    p_niwas_haveli: PLACEHOLDER_IMAGES.niwas,
    p_calangute_beach: PLACEHOLDER_IMAGES.calangute,
    p_basilica_bom_jesus: PLACEHOLDER_IMAGES.basilica,
    p_fort_aguada: PLACEHOLDER_IMAGES.fortAguada,
    p_spice_plantation: PLACEHOLDER_IMAGES.spicePlantation,
    p_anjuna_beach: PLACEHOLDER_IMAGES.anjuna,
    p_dudhsagar_falls: PLACEHOLDER_IMAGES.dudhsagar,
    p_palolem_beach: PLACEHOLDER_IMAGES.palolem,
    p_old_goa_churches: PLACEHOLDER_IMAGES.oldGoa,
    p_alleppey_backwaters: PLACEHOLDER_IMAGES.alleppey,
    p_munnar_tea_gardens: PLACEHOLDER_IMAGES.munnar,
    p_periyar_wildlife: PLACEHOLDER_IMAGES.periyar,
    p_padmanabhaswamy: PLACEHOLDER_IMAGES.padmanabha,
    p_kovalam_beach: PLACEHOLDER_IMAGES.kovalam,
    p_wayanad: PLACEHOLDER_IMAGES.wayanad,
    p_fort_kochi: PLACEHOLDER_IMAGES.fortKochi,
    p_ayurveda_kerela: PLACEHOLDER_IMAGES.ayurveda,
  };
  return mapping[poiId] || PLACEHOLDER_IMAGES.amberFort;
}
